practice/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.main, name = 'main'),
    path('create/', views.create, name = 'create'),
    path('read/<int:blog_pk>/', views.read, name = 'read'),
    path('update/<int:blog_pk>/', views.update, name = 'update'),
    path('delete/<int:blog_pk>/', views.delete, name = 'delete'),
    path('comment_update/<int:comment_id>/', views.comment_update, name = 'comment_update'),
    path('comment_delete/<int:comment_id>/', views.comment_delete, name = 'comment_delete'),
    path('hashtag_create/', views.hashtag_create, name = 'hashtag_create'),
]

practice/practice/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

practice/blog/models.py
from django.db import models

# Create your models here.

class Blog(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    reg_date = models.DateTimeField(auto_now_add=True)
    hashtags = models.ManyToManyField('Hashtag', blank=True)
    image = models.ImageField(upload_to = "images/", blank=True)

    def __str__(self):
        return self.title

class Comment(models.Model):
    post_id = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='comments')
    reg_date = models.DateTimeField(auto_now_add=True)
    content = models.CharField(max_length=50)

    def __str__(self):
        return self.content

class Hashtag(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name
    

practice/blog/forms.py
from django import forms
from django.forms import fields
from .models import Blog,Comment, Hashtag

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'content', 'hashtags', 'image']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

class HashtagForm(forms.ModelForm):
    class Meta:
        model = Hashtag
        fields = ['name']

practice/blog/views.py
from django.shortcuts import redirect, render, get_object_or_404
from .models import Blog, Comment, Hashtag
from .forms import BlogForm, CommentForm, HashtagForm
# Create your views here.

def main(request):
    blogs = Blog.objects
    return render(request, 'blog/main.html', {'blogs': blogs})

def create(request):
    if request.method == 'POST':
        form = BlogForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('blog:main')
    else:
        form = BlogForm()
        return render(request, 'blog/create.html', {'form' : form})

def read(request, blog_pk):
    blog = get_object_or_404(Blog, id = blog_pk)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.post_id = blog
            form.save()
            return redirect('blog:read', blog.pk)
    else:
        form = CommentForm()
        return render(request, 'blog/read.html', {'blog': blog, 'form': form})

def update(request, blog_pk):
    blog = get_object_or_404(Blog, id = blog_pk)
    if request.method == 'POST':
        form = BlogForm(request.POST, request.FILES, instance = blog)
        if form.is_valid():
            form.save()
            return redirect('blog:read', blog_pk)
    else:
        form = BlogForm(instance = blog)
        return render(request, 'blog/update.html', {'form' : form, 'blog_pk' : blog_pk})

def delete(request, blog_pk):
    blog = get_object_or_404(Blog, id = blog_pk)
    blog.delete()
    return redirect('blog:main')

def comment_update(request, comment_id):
    comment = get_object_or_404(Comment, id = comment_id)
    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            form.save()
            return redirect('blog:read', comment.post_id.id)
    else:
        form = CommentForm(instance=comment)
        return render(request, 'blog/comment_update.html', {'form' : form, 'comment_id' : comment_id})

def comment_delete(request, comment_id):
    comment = get_object_or_404(Comment, id = comment_id)
    comment.delete()
    return redirect('blog:main')

def hashtag_create(request):
    if request.method == 'POST':
        form = HashtagForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('blog:main')
    else:
        form = HashtagForm
        return render(request, 'blog/hashtag_create.html', {'form' : form})

practice/blog/templates/blog/comment_update.html
{% extends 'blog/main.html' %}

{% block content %}
    <form action="{% url 'blog:comment_update' comment_id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-outline-success">Success</button>
    </form>
{% endblock content %} 

practice/blog/templates/blog/create.html
{% extends 'blog/main.html' %}

{% block content %}
    <form action="{% url 'blog:create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-outline-success">Success</button>
    </form>
{% endblock content %} 

practice/blog/templates/blog/hashtag_create.html
{% extends 'blog/main.html' %}

{% block content %}
    <form action="{% url 'blog:hashtag_create' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-outline-success">Success</button>
    </form>
{% endblock content %} 

practice/blog/templates/blog/main.html
<!doctype html>
<html lang="ko">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'blog:main' %}">Home</a> 
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:create' %}">Create</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:hashtag_create' %}">Hashtag</a>
            </li>
            {% comment %} <li class="nav-item">
            <a class="nav-link" href="#">Pricing</a>
            </li>
            <li class="nav-item">
            <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
            </li> {% endcomment %}
        </ul>
        </div>
    </div>
    </nav>

    {% block content %}
        {% for blog in blogs.all %}
            <p><a href="{% url 'blog:read' blog.pk %}">{{ blog.title }}</a></p>
            <hr>
        {% endfor %}
    {% endblock content %}
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

practice/blog/templates/blog/read.html
{% extends 'blog/main.html' %}

{% block content %}
    <p>{{ blog.title }}</p>
    <img src="{{ blog.image.url }}" alt="My Image">
    <p>{{ blog.content }}</p>
    <p>{{ blog.reg_date }}</p>
    {% for hashtag in blog.hashtags.all %}
        <p>#{{ hashtag.name }}</p>
    {% endfor %}
    <div class="d-grid gap-2 d-md-block">
        <a href="{% url 'blog:update' blog.pk %}" class="btn btn-primary" type="button">수정</a>
        <a href="{% url 'blog:delete' blog.pk %}" class="btn btn-primary" type="button">삭제</a>
    </div>
    <h2>댓글</h2>
    <hr>
    {% for comment in blog.comments.all %}
        <p>{{ comment.content }}</p>
        <p>{{ comment.reg_date }}</p>
        <a href="{% url 'blog:comment_update' comment.id %}" class="btn btn-primary" type="button">수정</a>
        <a href="{% url 'blog:comment_delete' comment.id %}" class="btn btn-primary" type="button">삭제</a>
        <hr>
    {% endfor %}
    <form action="{% url 'blog:read' blog.pk %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-outline-success">댓글달기</button>
    </form>
{% endblock content %}

practice/blog/templates/blog/update.html
{% extends 'blog/main.html' %}

{% block content %}
    <form action="{% url 'blog:update' blog_pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-outline-success">Success</button>
    </form>
{% endblock content %}